# pandas e csv

## Resumo

Quase sempre quando formos "ler" um arquivo csv, vamos usar o pandas. É prático e bem eficiente.

## Funcionamento

Forma mais básica: (muitas vezes não usaremos a forma mais básica)
dataframe = pd.read_csv(arquivo_com_extensao)

- Vamos ler um arquivo real, com a Base de Dados de Vendas da Empresa "Contoso"

In [18]:
import pandas as pd

vendas_df = pd.read_csv('Contoso - Vendas - 2017.csv', sep=';')

vendas_df[:10]

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1
1,2,01/01/2017,06/01/2017,5,308,1586,2,18469,9,1
2,3,01/01/2017,01/01/2017,0,294,1444,5,19730,13,1
3,4,01/01/2017,01/01/2017,0,251,1468,5,29326,6,1
4,5,01/01/2017,07/01/2017,6,94,1106,2,22617,4,1
5,6,01/01/2017,01/01/2017,0,157,1046,2,7910,4,1
6,7,01/01/2017,09/01/2017,8,10,1261,2,11720,4,1
7,8,01/01/2017,05/01/2017,4,303,958,10,26558,4,1
8,9,01/01/2017,05/01/2017,4,213,1509,10,32396,8,1
9,10,01/01/2017,01/01/2017,0,199,1318,2,31290,8,1

# Aplicação